#!/bin/sh

# Set these paths appropriately

BIN=/var/www/html/simulationnarrative/python/tree-tagger/bin
CMD=/var/www/html/simulationnarrative/python/tree-tagger/cmd
LIB=/var/www/html/simulationnarrative/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
