#!/bin/sh

# Set these paths appropriately

BIN=/var/www/html/simulationnarrative/python/tree-tagger/bin
CMD=/var/www/html/simulationnarrative/python/tree-tagger/cmd
LIB=/var/www/html/simulationnarrative/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
