#!/bin/sh

# Set these paths appropriately

BIN=/var/www/html/simulationnarrative/python/tree-tagger/bin
CMD=/var/www/html/simulationnarrative/python/tree-tagger/cmd
LIB=/var/www/html/simulationnarrative/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
