#!/bin/sh

# Set these paths appropriately

BIN=/var/www/html/simulationnarrative/python/tree-tagger/bin
CMD=/var/www/html/simulationnarrative/python/tree-tagger/cmd
LIB=/var/www/html/simulationnarrative/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
