#!/bin/sh

# Set these paths appropriately

BIN=/var/www/html/simulationnarrative/python/tree-tagger/bin
CMD=/var/www/html/simulationnarrative/python/tree-tagger/cmd
LIB=/var/www/html/simulationnarrative/python/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
